### ISSUE TITLE
Format query output?

### ISSUE THREAD

**Issue by pieterjandesmedt** [thorning/mongoose-format#3]
I don't understand how query output formatting works, specifically the last step of the example.

For example, I have a database full of geojson points, but sometimes I just want to format the output as just the coordinates to reduce overhead, depending on the query parameter `format`.

Using expressjs, I have this the following code. Everything up till then works, adding the format to the model etc...
```
var Points = require('./point.model').point;

if(req.query.format == 'coords') {
	// This doesn't work / what do I have to do here ??    <-----------
	Points.format('coords', function (err, result) {
		console.log(result);
	});
} 

Points.find({}, function(error, results){
	if(error) {
		return res.json(500, error);
	} else {
		if(results == 1) results = { result: 'OK' };
		return res.json(200, results);
	}
});
```

The error I get is
```
TypeError: Cannot call method &#39;call&#39; of undefined
    at Function.format (/Users/pieterjandesmedt/Sites/tmc-api/node_modules/mongoose-format/lib/mongoose-format.js:50:45)
    at Object.exports.list [as handle] (/Users/pieterjandesmedt/Sites/tmc-api/routes/point/point.js:9:10)
    at next_layer (/Users/pieterjandesmedt/Sites/tmc-api/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/Users/pieterjandesmedt/Sites/tmc-api/node_modules/express/lib/router/route.js:107:5)
    at c (/Users/pieterjandesmedt/Sites/tmc-api/node_modules/express/lib/router/index.js:195:24)
    at Function.proto.process_params (/Users/pieterjandesmedt/Sites/tmc-api/node_modules/express/lib/router/index.js:251:12)
    at next (/Users/pieterjandesmedt/Sites/tmc-api/node_modules/express/lib/router/index.js:189:19)
    at Layer.shuttingDown [as handle] (/Users/pieterjandesmedt/Sites/tmc-api/server.js:79:10)
    at trim_prefix (/Users/pieterjandesmedt/Sites/tmc-api/node_modules/express/lib/router/index.js:226:17)
    at c (/Users/pieterjandesmedt/Sites/tmc-api/node_modules/express/lib/router/index.js:198:9)
```

Could you point me in the right direction? Thanks!

**Comment by thorning** [comment]
The formating have to be done explicitly after the query. In my project it is used purely for formating / cleaning data before I send it to the caller.
